### ISSUE TITLE
Changing Variables

### ISSUE THREAD

**Issue by rajp33** [karolkozer/planby#1]
Hi,
This is an awesome project that I stumbled upon. Very sleek and well documented! Kudos! 
While being able to render your own channel and program component is nice, would it be possible to be able to pass props to change some of the pre set variables referenced here:

https://github.com/karolkozer/planby/blob/320874a73be1c24b12d77b67bcf12f2d0a92aba2/src/Epg/helpers/variables.ts

**Comment by karolkozer** [comment]
Hi,

Thank you very much for your message. How did you find out about "Planby"?

Please tell me what variables would you like to overwrite? Maybe one of the future releases will include it.

What are your goals with regard to overwriting these variables? What you want to do?

**Comment by rajp33** [comment]
I found out about it while looking for libraries that made horizontal timelines possible. Many libraries that do so are outdated or don't look the best. I was thinking about creating my own but I needed something quick for a project I was working on. 

The project is a basketball game scheduler and it is going to be used to display the overall schedule of multiple teams playing each other at a round robin style tournament.

The variables I wanted to change was the width of the day, width of the hour, and height of the channels. 

I can try to make a PR if you are accepting them!

**Comment by karolkozer** [comment]
@rajp33 
Last week I started working on the feature to set custom height of the channels and programs and this functionality is almost finish.

In the same release I'll add the functionality to set up custom "dayWidth" property. So the measure of the hours will be calculated automatically because it depends on the "DAY_WIDTH" value eg. 
24h * 300px(your custom hour width) = 7200px -> dayWidth.

I am planning a new release next week.

**Comment by rajp33** [comment]
Awesome thank you!

**Comment by karolkozer** [comment]
@rajp33 
I decided to make two releases.
Yesterday, I made a release with itemHeight prop. You can check out this feature. 
Next week, I am going to make another release with dayWidth prop.

**Comment by karolkozer** [comment]
@rajp33 New version 0.1.32 with dayWidth prop has been released.

**Comment by rajp33** [comment]
Thank You!
