### ISSUE TITLE
Unnecessary requests are made on scroll.

### ISSUE THREAD

**Issue by ls-madhu** [karolkozer/planby#11]
Requests to the channel logos and other data are made unnecessarily on every scroll.

https://user-images.githubusercontent.com/90919727/178396050-c0db64f5-c38c-4414-9e20-c7b88f007ead.mp4

**Comment by karolkozer** [comment]
Hi @ls-madhu 

Thank you very much for your message.
The component does not send any request. These are links to pictures which are hide and not visible on a page. 
Every time on initial scroll there will be request for image from url, you can cached your image on the backend side.

**Comment by ls-madhu** [comment]
@karolkozer is there any way we can keep the complete EPG visible (without hiding and unhiding the images)?

**Comment by karolkozer** [comment]
EPG is based on custom virtual view because there would be too many elements on the page and the browser would crashed after a short time. So you can't keep all the channels and elements on the page.

**Comment by ls-madhu** [comment]
@karolkozer Oh thank you for the info. But due to that, navigation with `tab` is not working properly (focus goes to the next row even when there are more elements in the current row).
