### ISSUE TITLE
Problems with interface rendering

### ISSUE THREAD

**Issue by kfcx** [karolkozer/planby#13]
Hi author, I really like this project of yours, but I'm having serious problems with it  
The following is a non-normal rendered html code image, the first read renders no data, only a hot reload will restore it to normal
<img src="https://ik.imagekit.io/naihe/github/error.png">
https://ik.imagekit.io/naihe/github/error.png  

Here is a normally rendered html code image, only a hot reload renders the data
<img src="https://ik.imagekit.io/naihe/github/success.png">
https://ik.imagekit.io/naihe/github/success.png  
I'm a front-end noob and don't know how to fix it.

**Comment by karolkozer** [comment]
Hi @239144498 

Can you give me more info about your app?
- Are you using SSR?
- Are you using Next/Gatsby etc?

The first render could be empty cuz app has to calculate the dimensions of the container. Here is the example from Codepen. https://codesandbox.io/s/5o3tsy

I will try to recreate the problem.

**Comment by kfcx** [comment]
> 



> 

Thank you for your reply, let me tell you about the program
1. The program is running locally, I think I'm using SSR
2. I'm using React, not next

Sorry for the wait, I have just made a minimal reproduction environment, here is the demo from Codepen https://codesandbox.io/s/solitary-sound-by9r1p

Reproduction environment source code https://github.com/239144498/planby-test

Thank you so much for your help!

**Comment by karolkozer** [comment]
@239144498 
In your case please use fixed height and width in useApp props and remove styles from div.
https://codesandbox.io/s/naughty-minsky-7bmb57?file=/src/pages/Epgs.tsx

**Comment by kfcx** [comment]
> 

It's so exciting that he can now render the data properly, and I want to give you my highest thanks!
