### ISSUE TITLE
onScrollToNow cannot be executed

### ISSUE THREAD

**Issue by kfcx** [karolkozer/planby#14]
Hi author, I ran into a strange error

The onScrollToNow event does not execute properly after the button is clicked, I have tried other events such as onScrollTop and it works fine.  

The code added to the program is as follows

    const { ..., onScrollToNow, ... } = useApp();
    ...
     <IonButton onClick={() => { onScrollToNow(); }} >
        now
      </IonButton>

Here is a demo of the Codepen environment: https://codesandbox.io/s/optimistic-kate-x8rw1e

Front-end rookie requesting help.

**Comment by karolkozer** [comment]
Hi @239144498 

You are using data that has May dates (since and till). You must use today's data to use the "onScrollToNow" functionality.
Please read the documentation or see the demo page.
