### ISSUE TITLE
Typing issues using useEpg hook

### ISSUE THREAD

**Issue by GhostyJade** [karolkozer/planby#15]
Hey, I'm trying to integrate this package in my project (I'm using Typescript, react 18.2 and the latest version of planby).
While doing so, I've found that I can't get the hook working with the provided types:

![image](https://user-images.githubusercontent.com/38327334/192559140-da197dcf-70f8-4b42-9066-d0ff9ff8ec30.png)

I've found that in the useEpgProps, 
``` js
epg: Program[]; 
```

but the one imported from the default export is from dist/Epg/index.d.ts (imported as 'ProgramItem as ProgramItemType') and I think it's conflicting with the default type resolution.

![image](https://user-images.githubusercontent.com/38327334/192563447-ee708362-0bb7-4d86-944e-5b9851c51c27.png)

**Comment by karolkozer** [comment]
Hi @GhostyJade 
Can you give me the Codesandbox's link or the zip file to see the problem?

**Comment by GhostyJade** [comment]
Sure, [CodeSandbox](https://codesandbox.io/s/romantic-roentgen-nes0zz?file=/src/App.tsx)

**Comment by karolkozer** [comment]
Thanks for the Codesandbox code. There is an issue with assigned types: Program is assigned to ProgramItem instead of Program interface in the export file.

**Comment by GhostyJade** [comment]
Uhm, what I can do? c:

**Comment by karolkozer** [comment]
I have to make small fix for that.

**Comment by GhostyJade** [comment]
I mean, do u need help?

**Comment by karolkozer** [comment]
I will make changes and send you the version to check

**Comment by karolkozer** [comment]
@GhostyJade The bug has been resolved and released v1.1.1

Also, here is TS Codesandbox example: https://codesandbox.io/s/planby-epg-demo-ts-lp66v5?file=/src/App.tsx
