### ISSUE TITLE
Capturing line click event

### ISSUE THREAD

**Issue by PouyaKrm** [karolkozer/planby#16]
Hi, I'm trying to implement adding new program to the timeline by clicking specific place on the line and capture the time on that specific place to set program till property.
Is there any way to achieve this?

**Comment by karolkozer** [comment]
Hi @PouyaKrm 
Thanks for interested in Planby.

You can create blank items/programs in the EPG data and then you have possibilities to click on this blank item and get the start and till time. Component is based on data coming from external resources.

**Comment by PouyaKrm** [comment]
What about developing this feature?

**Comment by karolkozer** [comment]
Hi @PouyaKrm 
I suggested that this should be done in your EPG data. You have to add empty objects eg with id: 'blank-item' and since, till props in spaces between programs. You can only achieve this in that way because you specify data which are passed to the Component. Component is only a tool.

**Comment by karolkozer** [comment]
Maybe in the future there will be a plan to add function which will be checking spaces between programs inserting blank Item.
