### ISSUE TITLE
Change style of Line & add time to Line 

### ISSUE THREAD

**Issue by davistran86** [karolkozer/planby#18]
Hello and many thanks for this fantastic library, author! This library has been on my search list for a while :)

I want to customize style of Line component, such its color and width, but I'm not sure how. Would you kindly assist me?

Can we also have an option to display the current time at the top of the Line? Thank you, I truly need this for my project. Like the picture below:

![image](https://user-images.githubusercontent.com/23651625/200454912-102e365d-199f-4201-8294-687933199258.png)

**Comment by karolkozer** [comment]
Hi @davistran86 

How are you?

Thank you very much for your interest in "Planby". Sorry for the late reply but I was not available this week.

If you would like to change the color of the line you have to change the green value in the theme.
` green: {
    300: '#2C7A7B',
  },`
  Currently it is not possible to change the line width and display the current time at the top of the Line. I will consider it in the future release with the custom renderLine functionality.

**Comment by davistran86** [comment]
@karolkozer thanks, looking forward to it :)

**Comment by erganmedia** [comment]
If every UI element that is currently not customizable had a unique className, we would be able to style it within the globalStyles object. This could be a workaround until we have the custom renderLine functionality
