### ISSUE TITLE
How to not complete...

### ISSUE THREAD

**Issue by MwareSolutons** [karolkozer/planby#20]
Its not so easy to create exact sample as on your website.

Could you explain how to do the following: 

1. highlight programs that are live now
2. show the live line
3. scroll to the live programs

We are using it the for TV Guide data

**Comment by karolkozer** [comment]
Hi @MwareSolutons,
 
Thank you very much for your interest in "Planby". Sorry for the late reply but I was not available this week.

Please find below answers for your questions.

1. highlight programs that are live now
This function is only available for the programs that are on the current day. This is an automatic function that highlights the current live programs on a given day.  Also, please remember to set current date values in startDate and endDate props eg.  startDate: "2022-11-11T00:00:00", endDate: "2022-11-11T24:00:00".
Additionally, you can implement your own custom program component as it is described in the documentation or in the example "codesandbox". 
Documentation "renderProgram": https://github.com/karolkozer/planby#renderprogram
Codesnadbox: https://codesandbox.io/s/5o3tsy?file=/src/components/ProgramItem.js


2. show the live line
The live line is only available for programs from current day - this is automatic function out of the box. Please remember to set current date values in startDate and endDate props eg.  startDate: "2022-11-11T00:00:00", endDate: "2022-11-11T24:00:00".

3. scroll to the live programs
Scroll to now is only avaiable if you meet requirements from point "1".  This function is returned from useEpg hook.
Doc: https://github.com/karolkozer/planby#instance-properties

I hope these answers will help you.
