### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by IbreeqTech** [karolkozer/planby#21]
Hi Karol,
 
I’m currently working on using your EPG component on a project I’m working on. I’m running into an issue where when I pass in the time for any of the props you exposed using the useEPG hook I get the following error:

![image](https://user-images.githubusercontent.com/93386962/200925412-618dc6c1-2cf4-4e92-b27f-bffe3562bd6e.png)
![image](https://user-images.githubusercontent.com/93386962/200925440-3580ec56-e5c1-4290-9c16-5234d48fe96f.png)

`Transformed Data`
 
 
 
               
 
I’m using the following to transform my time value from a number in ms to the format you specified in your docs. However the only time the epg is actually working is when I’m passing in  static time stamps.
 
![image](https://user-images.githubusercontent.com/93386962/200925509-934a440f-5357-4b61-a533-4d0300a10a51.png)

`Code snippet where I’m formatting the dateTime`
 
Could you shed some light on what I can do to get past this issue?

**Comment by davistran86** [comment]
I'm using this and it's working:
```
format("YYYY-MM-DDTHH:mm:ss")
```

**Comment by IbreeqTech** [comment]
@davistran86  Unfortunately, i'm still getting the same error.

**Comment by IbreeqTech** [comment]
@davistran86 @karolkozer  I've actually figured it out. For `till` and `since` my data actually had some bad time for some reason and when transformed would return `invalid time`. I simply didn't see it until today.

The issue with `startDate` and `endDate` is that I suppose is that you only want the date and no specific time. So I simply passed the date at 00:00 and 24:00.
