### ISSUE TITLE
the indicator line is not visible when program data is provided for 48 hours and when next js server rendering on page reload the indicator line goes back 5 and a half hours(UTC) before the local time.

### ISSUE THREAD

**Issue by dghoshCinedigmInd** [karolkozer/planby#22]
the indicator line is not visible when program data is provided for 48 hours and when next js server rendering on page reload the indicator line goes back 5 and a half hours(UTC) before the local time.

Hence, need your help to resolve these issue. Please let me know if you need any additional information from my end.

**Comment by karolkozer** [comment]
Hi,

Thank you very much for your interest in Planby.

"the indicator line is not visible when program data is provided for 48 hours"
The data provided to the EPG can only be for 24 hours - 1 day. 

"when next js server rendering on page reload the indicator line goes back 5 and a half hours(UTC) before the local time."
Data must be converted from UTC to local time before adding it to useEPG
Please provide link do CodeSandbox
