### ISSUE TITLE
React Native version

### ISSUE THREAD

**Issue by Lucky-spirit** [karolkozer/planby#24]
Hi everyone!
Do you have plans for a React Native version?

**Comment by karolkozer** [comment]
Hi @Lucky-spirit ,

Thank you very much for your interest in Planby.
Currently, there are no plans for a React Native version.

**Comment by Lucky-spirit** [comment]
Hi @karolkozer ,
Thank you very much for the quick response. 🙂
Have a good day!👋

**Comment by karolkozer** [comment]
@Lucky-spirit The work for React Native is in progress and we have a plan for beat release in the near future.

https://github.com/user-attachments/assets/64209a9c-6967-44ac-9603-3bf4c95030d3

**Comment by karolkozer** [comment]
Planby Native Beta is now available for free for testing
Check it out: https://github.com/karolkozer/planby/issues/75

@Lucky-spirit
