### ISSUE TITLE
is this possible to have a vertical view?

### ISSUE THREAD

**Issue by mtoloto** [karolkozer/planby#25]
is there anyway to set this scheduler in vertical mode?

**Comment by karolkozer** [comment]
Hi @mtoloto ,

Thank you very much for your interest in Planby. 

Right now, there is no option for vertical mode. The main concept is to have this scheduler in horizontal mode.

But I will consider this request to my todo list in the future.

**Comment by mtoloto** [comment]
thanks @karolkozer !

sorry for my out of context question, do you know any daily schedule?

**Comment by karolkozer** [comment]
@mtoloto Maybe, this could be useful https://devexpress.github.io/devextreme-reactive/react/scheduler/
