### ISSUE TITLE
CRUD scheduling

### ISSUE THREAD

**Issue by florianbepunkt** [karolkozer/planby#26]
Question/feature request: Is it possible to add scheduling capabilities or use planby for a scheduling tool? I mean changing the channel of an item via drag and drop / editing the start and end of a program.

**Comment by karolkozer** [comment]
Hi @florianbepunkt ,

Thank you very much for your interest in Planby.

You can use "Planner" as a planning tool like in examples on the website. 
Planby is just a data processing tool that accepts data from the outside. There is no possibility and functionality "via drag and drop". 
Changes to the start and end of programs must be made before passing the data to the component.
