### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by rajp33** [karolkozer/planby#27]
Hi @karolkozer! Great project, started using it last year, I believe I had asked you to be able to edit the width of the timeline. I love the simplicity and the design of it, and recently forked it to make some changes that were required for my specific use case.

Wanted to use this issue as a checklist to create PRs for the features I added/want to add to the fork:

- [ ] Forward Refs to Content, Scrollbox, Channels, and Timeline
- [ ] Custom Loading Animation
- [ ] Support endless scroll (across multiple days)
- [ ] Demo for integration with DnD-Kit

**Comment by karolkozer** [comment]
Hi @rajp33 ,

Thank you very much for your interest in Planby.  I am glad to hear that you like the project!

I would like to inform you that:
 - custom loading - feature is done and will be available in the next release soon 
 - endless scroll - I have plan to implement this feature after next release, I prepared all the info to do that

**Comment by rajp33** [comment]
Hey @karolkozer I didn't get a chance to put up PRs for these but it looks like you already did this stuff! Very nice, love the work you did :)
