### ISSUE TITLE
Change interval of timeline from 24hr?

### ISSUE THREAD

**Issue by adamdevigili** [karolkozer/planby#3]
Hey there, awesome project! Well documented and easy to use. Was wondering if there was a way to override the 24hr default length of the timeline to a custom length/range (starting at 10:00 and going to 14:00 for example). Related, is there a way to override the 24hr time format to a more tradtional 12hr one (so 10:00am - 2:00pm for example)? 

Thanks again!

**Comment by karolkozer** [comment]
Hi, 
Thank you for your message. How did you find planby? 

Now, this functionality is not available but I am going to start working on it that you can specify date range eg. startDate and endDate(as optional property).

Probably it will be available in the next release.

**Comment by karolkozer** [comment]
@adamdevigili  There is a new release v0.2.0 with all your feature propositions: time range and possibility to change time to 12 hours (AM / PM).
https://github.com/karolkozer/planby/releases/tag/v.0.2.0
