### ISSUE TITLE
Feature Request : Option to set timeline dividers to daily, weekly, monthly

### ISSUE THREAD

**Issue by varunmulay22** [karolkozer/planby#30]
Hey Planby Team(@karolkozer ),

We wanted to take a moment to express our admiration for Planby. It has been an invaluable tool for our team as we use it to visualize due dates set by users in our video planning and editing app. The flexibility and customization options that Planby offers have been incredibly helpful for us and we are grateful for the work you have put into creating such a fantastic product.

As we continue to use Planby, we have identified a feature that we believe would further enhance its capabilities. Currently, the timeline dividers are set to hourly. However, we have identified a need for custom timeline dividers that include daily, weekly, and monthly options as well. We believe that this added feature would make Planby even more versatile and useful for a wider range of users and use cases.

An example would be such:

Pre-production date: Feb 27th, 2023
Production date: March 12th, 2023
Post-production: March 15th, 2023
...

For the above we would visualize the date type as channels and the dates as programs associated with the channels

We would love to know your thoughts on this feature request and would be happy to contribute in any way that we can to help make it a reality. We understand that developing new features takes time and resources, so we want to make sure that this is something that aligns with your vision for Planby before we proceed.

Please let us know your thoughts and if there is anything we can do to assist with this request. Thank you.

**Comment by karolkozer** [comment]
Hi @varunmulay22 

Thank you very much for your interest in Planby. I am glad to hear that Planby meets all your project requirements and helps you develop your applications very easily.  I am still working on the component and pay due attention to make it high quality.

Could you send some simple graphics / designs about what is your vision for the component: daily, weekly, and monthly?
This will help me understand concept (do we understand this functionality in the same way). 
You can send me an email: karol.kozer@gmail.com.

I would say it is a really big new feature for the component but I see the future in this idea. It's important for me to listen to what the project/client requirements are to make Planby much better. I added this concept to my Todo list.

But before this functionality I have planned two other extensions and some fixes which should be done before this concept.

**Comment by varunmulay22** [comment]
Thanks @karolkozer , Ive initiated an email thread from our end with some graphics attached.

**Comment by karolkozer** [comment]
@varunmulay22 I sent you an email that this features are ready. Example on the website: https://planby.netlify.app/
