### ISSUE TITLE
Cannot go past 1 day

### ISSUE THREAD

**Issue by Fyb3roptik** [karolkozer/planby#32]
I set 
`startDate: 2023-02-09T11:24:50` and `endDate: 2023-02-10T10:24:50`
and I get Invalid time value

Do start and end date have to be on the same day? I am not seeing this documented anywhere. Thanks

**Comment by Fyb3roptik** [comment]
Disregard. I had isBaseTimeFormat set to true. Setting it to false fixed it! This repo is awesome thank you!

**Comment by Fyb3roptik** [comment]
Actually, it is now broken. I cannot scroll horizontally and I dont want it in 24hr format. Can you not go passed 1 day with 12 hour formatting?

**Comment by karolkozer** [comment]
Hey @Fyb3roptik 

You can add full clock hours only for startDate and endDate. The date should be only for 1 day.  Please see the isBaseTimeFormat option.
The endless scroll functionality for multiple days in the progress.

**Comment by Fyb3roptik** [comment]
Perfect thank you!

**Comment by karolkozer** [comment]
Hi @Fyb3roptik,

Endless scroll functionality is ready.
Right now, the feature for scrolling through multiple days is only available for Sponsors mode.
Demo: https://planby.netlify.app

**Comment by Fyb3roptik** [comment]
What an absolute badass 😁

**Comment by Ruttala-Lava-Raju** [comment]
Hi @karolkozer @Fyb3roptik ,

I have set
startDate: "2023-12-03T22:00",
endDate: "2023-12-04T08:00", and
isBaseTimeFormat: true,
and I get an invalid time value. 

Did I miss something? please help
