### ISSUE TITLE
Bug: isLine is not drawn on day ranges that contain two or more days

### ISSUE THREAD

**Issue by cckrause** [karolkozer/planby#36]
scenario: 
Define a date range which contain two different dates
startDate: `2022-02-02T12:00:00`
endDate: `2022-02-03T12:00:00`
isLIne: `true`

expected behavior:
The line gets drawn when the local time changes from `2022-02-02T23:59:59` to `2022-02-03T00:00:00`. Also the view is scrolled to the live edge if the given condition is met.

actual behavior:
The line is NOT getting drawn when the local time changes from `2022-02-02T23:59:59` to `2022-02-03T00:00:00`. The view is not longer scrolled to the live edge if the given condition is met.

Thx

**Comment by karolkozer** [comment]
Hi @cckrause,

Thank you very much for your interest in Planby component. 

It is not a bug. You can have only one day in the Timeline, range dates is not available, "endtDate" option description in the documentation.
startDate: 2022-02-02T12:00:00
endDate: 2022-02-02T24:00:00

Right now, the feature for scrolling through multiple days is only available for Sponsors mode.
Demo: https://planby.netlify.app
