### ISSUE TITLE
Scroll to specified time on mount

### ISSUE THREAD

**Issue by all-probros** [karolkozer/planby#38]
Normally component would directly scroll to current time, but I wanted it to stay at 00:00 
Is there any way to change this behavior this? like props :
`startAt: Date.now()`

**Comment by karolkozer** [comment]
Hi @all-probros,

Right now, there is not a functionality for that but you can use "onScrollLeft" function and set initial scroll.
I will add this to my Todo list.

**Comment by all-probros** [comment]
thanks alot!!
