### ISSUE TITLE
How do I override the styling of a specific component?

### ISSUE THREAD

**Issue by arcataroger** [karolkozer/planby#39]
Hi and thanks very much for making this library!  I've read through the docs and the examples, but I couldn't quite figure out to do this... hopefully a simple question?

Is there a way to override the styling on a specific component, like the hover color of a `<ProgramContent>`? I tried editing the theme file, and that let me change the `gradient` colors -- but that affects both the ProgramContent hover color and the timeline background.

I see that the programs have a class of `css-nsqzgd-ProgramContent`, but I'm not sure how to target that randomly generated `nsqzgd` part or what system is generating it.

In our codebase we're using MUI and `styled-components`, and I was able to wrap `<ProgramContent>` with a styled component and give it a `hover: { background: red !important}`, but that just doesn't seem like the right way of doing it.

Is there a built-in way to override CSS rules for a specific component?

Thank you!

**Comment by arcataroger** [comment]
I figured out part of the issue... it seems like `planby` uses `emotion` under the hood, and `styled-components` was conflicting with it. Once I used the `styled` from `emotion` in this file, I was able to make a `<StyledProgramContent>` that overrode the hover color without needing `!important`.

But this still requires a custom `Program` via `renderProgram`. Is there any way to just override the CSS (like from the `globalStyles` prop) but targeting a specific component?

**Comment by karolkozer** [comment]
Hi @arcataroger,

Thank you very much for your interest in Planby.

Right now, overwrite styles eg. StyledProgramContent is a workaround solution for that specific issue.
I have a request for similar solution with globaStyles eg. for Layout and Line. 
I am going to work on that feature on 25.03 but it will be available in sponsors plan.

**Comment by arcataroger** [comment]
Thanks for the response, @karolkozer!
