### ISSUE TITLE
renderTimeline not working/not implemented

### ISSUE THREAD

**Issue by Simba-Mupfunya** [karolkozer/planby#4]
It seems in the latest release 0.2.1 renderTimeline override just doesnt execute. First hint was styled component <TimelineDivider>
as written in the readme section not implemented within "planby" module

**Comment by karolkozer** [comment]
Hi, 

Thank you for your information regarding render Timeline func.

 I am going to check out and resolve this issue.

**Comment by karolkozer** [comment]
@Simba-Mupfunya hotfix for renderTimeline prop func has been released 0.2.2

**Comment by Simba-Mupfunya** [comment]
Works as expected, and this is a very impressive component in its virtualization and modular form.

**Comment by karolkozer** [comment]
That is great that everything works as you expected.
