### ISSUE TITLE
"Invalid time value" error when startDate to endDate > 1 day and `isBaseTimeFormat` = true

### ISSUE THREAD

**Issue by arcataroger** [karolkozer/planby#40]
Planby is crashing when the start to end date range exceeds 24 hours and `isBaseTimeFormat` is true:

![image](https://user-images.githubusercontent.com/11964962/226447257-e28b74ea-9c22-45bd-921c-399f32164b39.png)

I think this might be related to https://github.com/karolkozer/planby/issues/32 and https://github.com/karolkozer/planby/issues/5 ? If so, is the solution to:

- Sponsor the project for multi-day functionality (I'll ask the bosses about that!)
- Not use 12-hour time, OR keep `isBaseTimeFormat` set to false but then use custom `render` methods to show 12-hour time?

It seems like even in that case, though:

- Multi-day support in the documentation could be reworded, maybe? e.g. for the `endDate` prop, instead of "Endless scroll through multiple days available only for Sponsors" (which makes it sound like it's related to async endless loading), maybe "Must be within the same 24-hour period as `startDate`. Support for multiple days is available only to Sponsors"?
- The conflict with `isBaseTimeFormat` shouldn't crash the app? I'm not too sure how that prop works (it's just a boolean) but it seems like it's affecting both date input/parsing datestrings in addition to output formatting; the two should be separate concerns, I think?

I'm going to talk to my bosses about possible sponsorship, and then maybe spend some time in the source to see if I can help locate the crash issues.

Thanks again for this library!

**Comment by karolkozer** [comment]
I will fix it in v1.1.4. The app should not crash with isBaseTimeFormat set to true when day exceed 24h.

Good point with doc description. I will change the desc.

"I think this might be related to #32 and #5 ? If so, is the solution to:"
This version does not support the multiple days feature so you have to render your own custom component and add custom solutions to keep time format.

**Comment by arcataroger** [comment]
> I will fix it in v1.1.4. The app should not crash with isBaseTimeFormat set to true when day exceed 24h.

Thank you!!

> This version does not support the multiple days feature so you have to render your own custom component and add custom solutions to keep time format.

Do you mean "this version" as in the current release? Is it available in the sponsored version yet?

**Comment by karolkozer** [comment]
@arcataroger It is supported in sponsored version.

**Comment by karolkozer** [comment]
Bug has been already fixed in v1.1.4

@arcataroger thank you for report the bug and your reworded proposal connected with documentation description. 
I sent to you the invitation to the "Sponsors PRO" repo 🥳.
