### ISSUE TITLE
Error in Next.js

### ISSUE THREAD

**Issue by TymekV** [karolkozer/planby#42]
When I try example from [this codesandbox](https://codesandbox.io/s/5o3tsy) in my Next.js appliation it throws an error:

next-dev.js?878b:20 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `EPG`.

**Comment by karolkozer** [comment]
Hi @TiptoHub,

Which version of Next.js do you use? 
Do you use client or server components?
