### ISSUE TITLE
Can we use it for react-native?

### ISSUE THREAD

**Issue by angularDevru** [karolkozer/planby#43]
Hi, @karolkozer! The project is really good, Stated using it for the web and it is working fine, But for me, I need to use it in a react-native application is there any way to use the same library or is there any alternative library for the react-native application?

Thanks in advance!

**Comment by karolkozer** [comment]
Hi @angularDevru,

You can try use this library with React Native and tell me if it is working properly or what support/improvements should be to make it work properly.

**Comment by cruizg** [comment]
@angularDevru , Did you try with react-native?

**Comment by mahadev1990** [comment]
@cruizg - tried but it is not straightforward we have to change a lot of things.
such as existing react elements will not support, and scroll functionality will not support. basically, we have to change all the react elements to react-native elements.

**Comment by karolkozer** [comment]
Hi @mahadev1990 @angularDevru,

Thanks for your comment. 
What exactly would have to be replaced? Is the scrolling problem with focusing elements?
These info would be really helpful cuz I have in plans to extend Planby also to React Native

**Comment by karolkozer** [comment]
@angularDevru @mahadev1990 @cruizg The work for React Native is in progress and we have a plan for beat release in the near future.

**Comment by karolkozer** [comment]
Planby Native Beta is now available for free for testing
Check it out: https://github.com/karolkozer/planby/issues/75

@angularDevru @mahadev1990 @cruizg
