### ISSUE TITLE
Multi-day timeline labels don't match event dates?

### ISSUE THREAD

**Issue by arcataroger** [karolkozer/planby#44]
For multi-day views (like in the sponsored repo), it seems like the timeline sometimes renders the wrong dates?

![image](https://user-images.githubusercontent.com/11964962/232134417-fdc35e56-a1f0-4e0f-9fa0-c1c08d68af43.png)

Demo here:
https://planby-multiday-test.vercel.app/

Minimal reproducible example here:
https://github.com/arcataroger/planby-multiday-test (private because it uses the sponsored version, but invited @karolkozer to it)

But relevant code and data here:
https://gist.github.com/arcataroger/9173f1821fe5e5f84994cea61553618e

**Comment by karolkozer** [comment]
@arcataroger please create an issue in the private repo

**Comment by karolkozer** [comment]
<img width="1223" alt="Screenshot 2023-04-16 at 18 01 13" src="https://user-images.githubusercontent.com/29305289/232325261-22f915ab-72b5-4bde-a3e7-3a26a632d821.png">
Dates are okay.

**Comment by karolkozer** [comment]
I see that it is working correctly on your demo page https://planby-multiday-test.vercel.app/, please see the screenshots.
Maybe it is something with timezones. 
What time zone are you in? I will investigate what is wrong and make some updates.

**Comment by arcataroger** [comment]
@karolkozer Sorry, how do I access the private repo? I don't seem to have permission.

We are in Pacific Daylight Time (`America/Los_Angeles` or UTC-7 to UTC-8 depending on Daylight Savings). I tried to locally change my computer time zone to UTC/GMT and it went away. Set to London or UTC+1 (`Africa/Lagos`), the problem disappears. Setting it to `Atlantic/Cape_Verde` (UTC-1) makes the problem start.

I would be happy to report this and help debug it in the private repo once I can access it.

Thanks!

**Comment by seetha-rv** [comment]
@karolkozer can you please help give access to the private repo for Roger. I have sent u a separate email on this. Appreciate the help very much.
