### ISSUE TITLE
TimeLine after 24h keep counting 25,26,27...

### ISSUE THREAD

**Issue by KlajdiTolis** [karolkozer/planby#45]
Hello,
I am using Planby lately and i really appreciate your work but i have some problems with timeline . When the difference of startTime and endTime is larger then 24h (1day) the timeline keep counting 25,26,27... and not starting from 0 again .
Can you suggest me any solution ?
Thank you!
![image](https://user-images.githubusercontent.com/110922024/236471325-eb7f172b-612c-45fb-b42b-adf40cdd74e2.png)

**Comment by karolkozer** [comment]
Hi @KlajdiTolis,

Thanks for your interest in "Planby" component.

Scroll through multipledays (and other features) is only avaiable for Sponsors.
In the docs is description about "endDate" prop.
``Date format 2022-02-02T00:00:00. , 2022-02-02T:20:00 etc. Must be within the same 24-hour period as startDate. Full clock hours only. Scroll through multiple days is available only in Sponsors plan``
