### ISSUE TITLE
Feature Request: Single-channel/track program/event list

### ISSUE THREAD

**Issue by wedebe** [karolkozer/planby#46]
I can't believe how much fun this is! I've seen cool stuff added since last time I checked out the demo - thanks so much :)

Have/would you consider a single set of entries listed with associated details? The concept being that a user clicks on (for example) a channel logo, which then presents a more detailed listing of its own?

A mockup would explain this way better than I can elucidate:
<img width="744" alt="Click" src="https://github.com/karolkozer/planby/assets/9741693/9f310579-5f04-418e-afff-f6c079b6abb0">

<img width="744" alt="Result" src="https://github.com/karolkozer/planby/assets/9741693/94eecdf0-9604-424c-9886-ef6fd02689db">

**Comment by karolkozer** [comment]
Hi @wedebe,

This is more custom feature that you can implement on your own but I can consider this in my "Todo" list to add some "onClick" events.
