### ISSUE TITLE
Request to get the code on caledar planner example used in https://planby.netlify.app/

### ISSUE THREAD

**Issue by damadigit** [karolkozer/planby#48]
this is not exactly an issue with the software but request to share us the code used to build calendar planner examaple on https://planby.netlify.app/ 
![image](https://github.com/karolkozer/planby/assets/115228958/3c2c1b46-676b-45da-a392-ee56fca7b2cc)

Thankyou in advance

**Comment by karolkozer** [comment]
Hi @damadigit,

I can prepare the demo code for this but the vertical mode is only available in Sponsors option.

**Comment by damadigit** [comment]
it seems great product, too bad i can't sponsor, because credit cards or any other means to setup billing are not avaialable where i am from.  
for now [this library ](https://www.npmjs.com/package/react-big-calendar) will do the work

Thankyou and keepup the good work.

**Comment by damadigit** [comment]
it seems great product, too bad i can't sponsor, because credit cards or any other means to setup billing are not avaialable where i am from.
for now [this library ](https://www.npmjs.com/package/react-big-calendar)will do the work

Thankyou and keepup the good work.
