### ISSUE TITLE
Grouping/Tree Data for Planner? 

### ISSUE THREAD

**Issue by vanta240i** [karolkozer/planby#49]
I want to be able to group objects under one, or better said make a tree system where one planner is under another.
![image](https://github.com/karolkozer/planby/assets/102895212/c7910a73-9539-4223-8aa4-675dd34c9aca)
For example, Auditorium D in this scenario has rooms under it. I would appreciate the ability to create something like this where I am able to sort items under another, since in my software, we need to see what employees under an employee are doing, and having this grouping system would be very nice.

Compared to the screenshot, I would actually appreciate it more if there was an option to not add events for Auditorioum D in that instance, and rather only to the items under it, since I don't want to be able to add events to the actual employee, but rather to the employees under that employee.

**Comment by karolkozer** [comment]
Hi @octavian-ene,

Thanks for your idea for the feature. Let me analyze this request. There will be some work to implement this rooms under the item and integrate with the virtual timeline layout. 

But I think will be easier to add the rooms to the events to the Auditorium D like in the example below
```
const rooms = React.useMemo(
  () => [
    {
title: 'Auditorium D',
      logo: 'https://via.placeholder.com',
      uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
      events: [
    {
    title: 'Room D1'
  logo: 'https://via.placeholder.com',
      uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
...
},
 {
title: 'Room D2'
  logo: 'https://via.placeholder.com',
      uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
...
},

        ]
      ...
    },
  ],
  []
);
```

**Comment by vanta240i** [comment]
> Hi @octavian-ene,
> 
> Thanks for your idea for the feature. Let me analyze this request. There will be some work to implement this rooms under the item and integrate with the virtual timeline layout.
> 
> But I think will be easier to add the rooms to the events to the Auditorium D like in the example below
> 
> ```
> const rooms = React.useMemo(
>   () => [
>     {
> title: 'Auditorium D',
>       logo: 'https://via.placeholder.com',
>       uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
>       events: [
>     {
>     title: 'Room D1'
>   logo: 'https://via.placeholder.com',
>       uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
> ...
> },
>  {
> title: 'Room D2'
>   logo: 'https://via.placeholder.com',
>       uuid: '10339a4b-7c48-40ab-abad-f3bcaf95d9fa',
> ...
> },
> 
>         ]
>       ...
>     },
>   ],
>   []
> );
> ```

Is what you commented on in the example already available? Or is it to be implemented?

**Comment by karolkozer** [comment]
This is the concept and then I will start implementation process.

**Comment by vanta240i** [comment]
Hi, I'm still looking for a planner. Are there any updates on this?

**Comment by karolkozer** [comment]
Hi @m1daz 
I planned work connected with grouping tree on December/January.

**Comment by vanta240i** [comment]
Awesome. Should I close this issue?

**Comment by karolkozer** [comment]
@m1daz 

https://github.com/karolkozer/planby/assets/29305289/26c66368-21b5-4fe2-8a1a-5da5d0dc5dad


I am finishing the group tree feature. Please find the short video.

**Comment by karolkozer** [comment]
@m1daz send me an email and I will add you to the beta version: contact@planby.app
