### ISSUE TITLE
Try out initialScrollPositions feature

### ISSUE THREAD

**Issue by emilehay** [karolkozer/planby#51]
Hey karolkozer,

I love Planby and I'm trying to use it for an EPG timeline in a React application on smart TVs. I've got an issue where I'd like to switch pages and come back to the same position in the planby grid as I was before. I noticed that there's an initialScrollPositions property that I might be able to use for this purpose.

Is there any way I can confirm that this would work? If it does, I think I can convince my company to become a sponsor for this project! Let me know.

**Comment by karolkozer** [comment]
Hi @emilehay,

Thank you for your interest in Planby. I am glad to hear that. 
I can add you to the PRO version for trial period eg. 1 or 2days so you can test and confirm that initialScrollPositions props works properly.

**Comment by emilehay** [comment]
Hi @karolkozer,

Thanks for your swift reply. That sounds perfect! I don't need long to test my use case. Let me know what you need from me.

**Comment by karolkozer** [comment]
@emilehay I added you to the PRO version

**Comment by karolkozer** [comment]
@emilehay Did you test the initialScrollPositions props?

**Comment by emilehay** [comment]
Hi @karolkozer,

Thank you very much!

I tried it today and initially ran into problems, it seems Planby didn't like the EPG data from my Redux store for reasons I don't fully understand, but eventually, I managed a workaround by using `JSON.parse(JSON.stringify(epg))`.

Unfortunately, I'd already left the office when I finally managed so I'll only be able to confirm on actual TV devices tomorrow, but I can confirm that it does work beautifully on my browser.

**Comment by karolkozer** [comment]
@emilehay have you tested everything?

**Comment by emilehay** [comment]
I have, thank you @karolkozer. My company will certainly be sponsoring Planby. I'm going through the process now of getting a GitHub account set up that we'll be using.

Thank you again for the great tool and for letting us try out the pro features!
