### ISSUE TITLE
Possible to have events that stack or layer 

### ISSUE THREAD

**Issue by hungrysquirrel** [karolkozer/planby#52]
Hello Planby, super cool project. Is it possible that your software supports stacking or overlapping events as seen in the example image?

![image](https://github.com/karolkozer/planby/assets/232397/b32cd8c6-e440-4340-bc4b-6ff1ec670c78)

**Comment by karolkozer** [comment]
Hi @hungrysquirrel

Right now, I am working on overlapping feature with "stack" and "squeeze" options. 

What do you mean by "stacking"?

<img width="1718" alt="Screenshot 2023-08-24 at 16 22 14" src="https://github.com/karolkozer/planby/assets/29305289/3d22e1fd-7dca-4397-9bcf-82651ec95827">

<img width="1722" alt="Screenshot 2023-08-24 at 16 25 19" src="https://github.com/karolkozer/planby/assets/29305289/ae8b10ce-0036-4aad-b336-9358025500b4">

**Comment by hungrysquirrel** [comment]
@karolkozer by stacking I mean layering z-index like the example I attached in my first query. 
Thanks for showing me examples of what you are working on...cool to see those too. LMK about the z-indexing stack option.

**Comment by karolkozer** [comment]
@hungrysquirrel do you think about something like that behaviour?
<img width="1716" alt="Screenshot 2023-08-24 at 17 16 29" src="https://github.com/karolkozer/planby/assets/29305289/7f9e9e01-9393-4316-8740-eb864483865f">

**Comment by hungrysquirrel** [comment]
@karolkozer thanks for sharing another example...IMO I like the first two maybe with the ability to expand a stack...if I could set a threshold of what to visualize before condensing into something like +5 more.

Same thinking applies to the later example...if many events overlap I would want a way to communicate that and again provide a way to expand so by default the timeline is not overwhelmed.

**Comment by phola** [comment]
> Hi @hungrysquirrel
> 
> Right now, I am working on overlapping feature with "stack" and "squeeze" options.
> 
> What do you mean by "stacking"?
> 
> <img alt="Screenshot 2023-08-24 at 16 22 14" width="1718" src="https://user-images.githubusercontent.com/29305289/263004001-3d22e1fd-7dca-4397-9bcf-82651ec95827.png"> <img alt="Screenshot 2023-08-24 at 16 25 19" width="1722" src="https://user-images.githubusercontent.com/29305289/263004542-ae8b10ce-0036-4aad-b336-9358025500b4.png">

Hi, great project thanks! I'm also interested in this feature (especially the stack option) - any update on progress (happy to help too) ?

**Comment by karolkozer** [comment]
Hi @phola,

The work is in progress, I am resolving some issues. The feature will be ready in the near future.

**Comment by karolkozer** [comment]
@hungrysquirrel I finished the layer overlaps. It looks like in the example below
<img width="1714" alt="Screenshot 2023-09-10 at 18 55 16" src="https://github.com/karolkozer/planby/assets/29305289/b6df3bfb-1267-4a8e-994d-42fa00a755c3">

**Comment by hungrysquirrel** [comment]
@karolkozer nice....thank you when will this be available? 
are there display options that come with the new feature, is overlap a boolean on the row...are there other options similar to your stack & squeeze?

**Comment by karolkozer** [comment]
@hungrysquirrel it is still in testing face, I have to fix some issue with dnd in vertical mode.  I think at end of this month will be a beat version. 
There will be overlaps option like stack, layer (with option on percentage of covering) and maybe squeeze.
In the layer option when you hover on the element it will be fully visible (highest z-index in the overlaps group)

**Comment by karolkozer** [comment]
@hungrysquirrel @phola  Beta 3.5.0 version is live 😄 
https://planby.netlify.app/

**Comment by karolkozer** [comment]
@hungrysquirrel @phola  in next releases will be resize element and drag and drop multi rows features
The dnd multi-row feature is almost done

https://github.com/karolkozer/planby/assets/29305289/c01a9524-e02d-4890-abbc-4605c716fd74

**Comment by karolkozer** [comment]
@hungrysquirrel @phola  Dnd multi-rows mode is live https://planby.netlify.app/
