### ISSUE TITLE
Possible to drag and drop program

### ISSUE THREAD

**Issue by wenwei-lin** [karolkozer/planby#53]
Hi @karolkozer, your project is so cool! I want to use it in my project.

Is it possible to drag and drop the program and update the changes?

**Comment by karolkozer** [comment]
Hi @wenwei-lin,

The dnd with overlaps ,grid layout features are in beta version (Pro sponsors) and I have to prepare some code test examples.

**Comment by wenwei-lin** [comment]
@karolkozer Great! I'd like to try it~

**Comment by karolkozer** [comment]
@wenwei-lin Beta 3.5.0 version is live 😄 
https://planby.netlify.app/

**Comment by wenwei-lin** [comment]
@karolkozer Awesome!

Can I drag the program from one channel to another? Currently the drag and drop feature can only change the time of the program.

**Comment by karolkozer** [comment]
@wenwei-lin This is the first beta release, in next releases will be resize element and drag and drop multi rows features

**Comment by karolkozer** [comment]
@wenwei-lin The dnd multi-row feature is almost done

https://github.com/karolkozer/planby/assets/29305289/407dd20a-97d9-452c-b668-1e146c7a1e5d

**Comment by karolkozer** [comment]
@wenwei-lin Dnd multi-rows mode is live https://planby.netlify.app/

**Comment by wenwei-lin** [comment]
@karolkozer Awesome!
