### ISSUE TITLE
Touch events are supported? 

### ISSUE THREAD

**Issue by AntonioFacciutiCommit** [karolkozer/planby#55]
I tried the component in the demo from your site, but i see that the touch events don't work.
I have to implement they by myself or there are already developed into the premium version of the component?

Thanks in advance

**Comment by karolkozer** [comment]
Hi @AntonioFacciutiCommit,

These features like DnD, resize, calendar mode, multiple days etc. are available in PRO sponsors version.

**Comment by AntonioFacciutiCommit** [comment]
Sorry @karolkozer I misspoke, I mean if in DnD touch events are supported because in demo they don't work

**Comment by karolkozer** [comment]
Do you have in mind "DnD touch event" for mobile?

**Comment by karolkozer** [comment]
Update for mobile will be released in next version

**Comment by AntonioFacciutiCommit** [comment]
Thanks @karolkozer
