### ISSUE TITLE
Capturing the Epg click event to see the detail ?

### ISSUE THREAD

**Issue by hokhaminh** [karolkozer/planby#56]
Hello, everyone!
Thank you for creating such an awesome product.

I'm unsure how to implement the onClick event for an Epg item to display its details, similar to what is demonstrated in the demo page (referencing this picture)
![image](https://github.com/karolkozer/planby/assets/74462162/3ff8d753-2696-425b-91a0-0c23e42575d2)
 
 I'm not certain if this feature is exclusive to the PRO version, as I couldn't find its implementation in the [Codesandbox example](https://codesandbox.io/s/5o3tsy)
 
Could you please guide me on how to implement this functionality? Thank you so much!

**Comment by karolkozer** [comment]
Hi @hokhaminh,

 In order to implement the on click event on the program you have to render custom program and pass to this program onClick event which will trigger the opening the modal. Modal is not part of the Planby component, you need to implement this feature by yourself.

**Comment by hokhaminh** [comment]
Thank you for your support
