### ISSUE TITLE
DND overlay changes and card lock

### ISSUE THREAD

**Issue by WtfLaika** [karolkozer/planby#57]
Hi @karolkozer! Wonderful project, I started to work with your library recently. The API looks great, it's easy to understand, and to customize. But I have several questions, about how to get some features:

- [ ]  Is it possible to lock a few cards to have the opportunity to drag and drop them all at once?
- [ ]  When I move a  card to a small gap, the row is getting extended. Is it possible to restrict row extension and just move the card back to the initial position in this case?
- [ ] The same with card resizing, if the user tries to resize a card and does not have enough space - the row extends. It is possible to restrict row extension in this case too?

**Comment by karolkozer** [comment]
Hi @WtfLaika 

Thank you very much for your interes in Planby component!

-  **Is it possible to lock a few cards to have the opportunity to drag and drop them all at once?** 
No
- **When I move a card to a small gap, the row is getting extended. Is it possible to restrict row extension and just move the card back to the initial position in this case?** 
Can you send a screen recording? It helps me to understand your question and give you the anserw
- **The same with card resizing, if the user tries to resize a card and does not have enough space - the row extends. It is possible to restrict row extension in this case too?** 
You can disable the `overlap` option to restrict row extension
