### ISSUE TITLE
Is it possible to scroll to "Now Time" on page mount?

### ISSUE THREAD

**Issue by Ruttala-Lava-Raju** [karolkozer/planby#58]
Hi @karolkozer,

We wanted to show the **Now Time** line next to the sidebar.
Is there any way to handle this?

**Required UI**: 
![image](https://github.com/karolkozer/planby/assets/88703564/20fb62da-2464-4982-be08-feb7d0b88ad6)

**Comment by karolkozer** [comment]
Hi @Ruttala-Lava-Raju,

You can do this by using the custom scroll function `onScrollRight` and calculate the value X.

**Comment by Ruttala-Lava-Raju** [comment]
@karolkozer  Thank you

**Comment by Gizmeondevwip** [comment]
@Ruttala-Lava-Raju Could you please paste the code to achive this?
