### ISSUE TITLE
Issues with resizeMouseUp and dragMouseUp Events

### ISSUE THREAD

**Issue by shahnewaz-gain** [karolkozer/planby#60]
I tried to resize and drag the program, but these actions give me old times instead of displaying the correct times. 

**Note**
The issues appeared after adding those events.

**Comment by karolkozer** [comment]
Hi @shahnewaz-gain,

Please create an issue in the Planby PRO repo

**Comment by karolkozer** [comment]
Hi,

Please create an issue in the Planby PRO repo.

Best
Karol
