### ISSUE TITLE
Facing issue with version 3.7.0

### ISSUE THREAD

**Issue by emon-gain** [karolkozer/planby#61]
1. Resizing issue: 
  resizeMouseUp event gives me initial time after rising, and it works fine after removing this event. However, I need the updated resized time.
2. Dragging issue:
   How can I get the updated channel information of the dragged program? I'm currently using this 'dragMouseUp' event, which gives me just program details, but I also need updated channel details.
3. How can I hide current timeline bar?

**Comment by karolkozer** [comment]
Hi @emon-gain,

Please create an issue in the Planby PRO repo.
