### ISSUE TITLE
Do we have the code sandbox example for Calander View (Horizontal view)?

### ISSUE THREAD

**Issue by Ruttala-Lava-Raju** [karolkozer/planby#66]
![image](https://github.com/karolkozer/planby/assets/88703564/ad37f9d7-d9f2-4635-a10a-829acdbeaad4)

**Comment by Ruttala-Lava-Raju** [comment]
Duplicate of https://github.com/karolkozer/planby/issues/48

**Comment by karolkozer** [comment]
Hi @Ruttala-Lava-Raju,

All the code examples are only available in the PRO plan.

**Comment by Ruttala-Lava-Raju** [comment]
Thank you for the update😊
