### ISSUE TITLE
Should not inject global styles

### ISSUE THREAD

**Issue by shuding** [karolkozer/planby#7]
Thanks for making this library! I noticed that it will always inject global styles including a web font when rendered. This makes the component look nicer but it affects other parts of the application.

It would be great to scope some of the styles to the component itself, and let the user to add the global styles and fonts by themselves.

**Comment by karolkozer** [comment]
Hi @shuding 

Thank you very much for your message. Great point about injection of global styles and fonts.

I would be grateful if you could give examples of what the styles and font properties passed to the component would look like? 
You can describe more in details how would you like to scope some of the styles to the component itself.
